repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: ^.*(project|migrations|data_models\.py).*$
        args: ["--max-line-length=88", "--extend-ignore=E226,E203,W503"]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        exclude: migrations

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: migrations
        args: ["--profile", "black"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ push ]
