repos:
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        args: ["--extend-ignore=E501,E226,E203"]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: migrations


