# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

version: "3.8"
services:
  pantportal:
    user: "75130:1000" # Override in docker-compose.override.yml if local user is different
    container_name: esani_pantportal
    image: esani-pantportal:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./dev-environment/esani-pantportal.env
    volumes:
      - ./esani_pantportal/:/app
      - ./dev-environment/cert:/ssl:ro
    depends_on:
      - pantportal-db
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - TEST=false
    network_mode: "host"  # Kun nødvendig i dev-environment for at få test-idp til at fungere
    command: gunicorn -b 0.0.0.0:8000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  pantportal-db:
    container_name: pantportal-db
    image: postgres:16
    env_file:
      - ./dev-environment/esani-pantportal.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: "host"  # Kun nødvendig i dev-environment for at få test-idp til at fungere

  pantportal-test-idp:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    image: kenchan0130/simplesamlphp
    container_name: pantportal-test-idp
    network_mode: "host"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:8000/saml/metadata/
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8000/login/callback/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:8000/logout/callback/
      SIMPLESAMLPHP_IDP_CERTIFICATE: /var/www/simplesamlphp/cert/selfsigned.crt
      SIMPLESAMLPHP_IDP_PRIVATEKEY: /var/www/simplesamlphp/cert/selfsigned.key

    volumes:
      - ./dev-environment/cert/idp/selfsigned.crt:/var/www/simplesamlphp/cert/server.crt:ro
      - ./dev-environment/cert/idp/selfsigned.key:/var/www/simplesamlphp/cert/server.pem:ro
      - ./dev-idp/authsources.php:/var/www/simplesamlphp/config/authsources.php:ro
      - ./dev-idp/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php:ro

volumes:
  postgres-data:
