# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

version: "3.8"
services:
  pantportal:
    user: "1000:1000" # Override in docker-compose.override.yml if local user is different
    container_name: esani_pantportal
    image: esani-pantportal:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./dev-environment/esani-pantportal.env
    volumes:
      - ./esani_pantportal/:/app
      - ./dev-environment/cert:/ssl:ro
      - ./data/qr_codes:/srv/media/qr_codes
      - ./data/deposit_payouts:/srv/media/deposit_payouts
    depends_on:
      - pantportal-db
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - TEST=false
      - SKIP_IDP_METADATA=true
    ports:
      - "8000:8000"
    networks:
      - postgres
      - sftp
    command: gunicorn -b 0.0.0.0:8000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  pantportal-db:
    container_name: pantportal-db
    image: postgres:16
    env_file:
      - ./dev-environment/esani-pantportal.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

  pantportal-cron:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: pantportal-cron
    image: esani-pantportal:latest
    depends_on:
      - pantportal-db
    env_file:
      - ./dev-environment/esani-pantportal.env
    volumes:
      - ./esani_pantportal/:/app
      - ./data/product_lists:/srv/media/product_lists
      - ./dev-environment/crontab:/crontab
    networks:
      - postgres
      - sftp
    entrypoint: [ ]
    command: [ "supercronic", "/crontab" ]

  pantportal-sftp:
    image: atmoz/sftp
    volumes:
        - ./data/product_lists:/home/sftp_tomra/product_lists
        - ./data/deposit_payouts:/home/sftp_tomra/deposit_payouts
        - ./dev-environment/users.conf:/etc/sftp/users.conf
    ports:
        - "2222:22"
    networks:
      - sftp

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none' # Disable saving logs
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP port
    networks:
      - postgres

volumes:
  postgres-data:

networks:
  postgres:
    name: postgres
  sftp:
    name: sftp
