version = 1
SPDX-PackageName = "ESANI Pantportal"
SPDX-PackageSupplier = "Magenta ApS <info@magenta.dk>"

[[annotations]]
path = ["REUSE.toml", "dev-environment/**", "esani_pantportal/requirements.txt", "esani_pantportal/.coveragerc", "esani_pantportal/barcode_scanner/static/images/**", "esani_pantportal/esani_pantportal/migrations/**", ".gitignore", ".gitlab-ci.yml", ".pre-commit-config.yaml", "data/**", "esani_pantportal/esani_pantportal/templates/esani_pantportal/**/actions.html", "esani_pantportal/esani_pantportal/templates/esani_pantportal/**/select.html", "esani_pantportal/esani_pantportal/clients/tomra/data_models.py", "esani_pantportal/mypy.ini"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Magenta ApS <info@magenta.dk>"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = ["esani_pantportal/esani_pantportal/static/bootstrap/**", "esani_pantportal/barcode_scanner/static/bootstrap/**.map"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2023 The Bootstrap Authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["esani_pantportal/esani_pantportal/static/jquery/**", "esani_pantportal/barcode_scanner/static/jquery/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "OpenJS Foundation and other contributors, https://openjsf.org/"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Magenta ApS <info@magenta.dk>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "esani_pantportal/esani_pantportal/static/bootstrap-table/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2023 The Bootstrap-table Authors"
SPDX-License-Identifier = "MIT"
