# Generated by Django 4.2.2 on 2023-11-28 15:59

from django.db import migrations, models
import django.db.models.deletion
import esani_pantportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('from_date', models.DateField(db_index=True, verbose_name='Fra-dato')),
                ('to_date', models.DateField(db_index=True, verbose_name='Til-dato')),
                ('item_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositPayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField()),
                ('rvm_serial', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('barcode', models.CharField(validators=[esani_pantportal.models.validate_barcode_length, esani_pantportal.models.validate_digit])),
                ('count', models.PositiveIntegerField()),
                ('company_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='esani_pantportal.companybranch', verbose_name='Butik')),
                ('deposit_payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esani_pantportal.depositpayout')),
                ('kiosk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='esani_pantportal.kiosk', verbose_name='Kiosk')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='esani_pantportal.product', verbose_name='Produkt')),
            ],
        ),
    ]
