# Generated by Django 4.2.2 on 2023-10-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Emballagens tiltænkte volumen i Milliliter', verbose_name='Volumenkapacitet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.PositiveIntegerField(default=0, help_text='Emballagens diameter i Millimeter', verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='Emballagens højde i Millimeter', verbose_name='Højde'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_type',
            field=models.CharField(choices=[('P', 'PET'), ('A', 'Aluminium'), ('S', 'Stål'), ('G', 'Glas')], default='P', help_text='Materialetype', verbose_name='Materialetype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('F', 'Flaske'), ('A', 'Anden')], default='B', help_text='Kategori for emballagens form. Flasker er "Bottles", andre ting er "Other"', verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Tør/tom vægt af emballagen i Gram', verbose_name='Vægt'),
        ),
    ]
