# Generated by Django 4.2.2 on 2023-12-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0005_alter_product_shape_product_height_constraints_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundmethod',
            options={'ordering': ['serial_number'], 'verbose_name': 'refundmethod', 'verbose_name_plural': 'refundmethods'},
        ),
        migrations.AlterField(
            model_name='refundmethod',
            name='method',
            field=models.CharField(choices=[('FK', 'Flaskeautomat m/komprimator'), ('FS', 'Flaskeautomat m/sikkerhedscontainer'), ('FKS', 'Flaskeautomat m/komprimator m/sikkerhedscontainer'), ('S', 'Sække'), ('M', 'Manuel sortering'), ('A', 'Anden')], help_text='Måden at pant bliver registreret på', verbose_name='Pantmetode'),
        ),
    ]
