# Generated by Django 4.2.2 on 2023-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0006_alter_refundmethod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approved',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nej')], default=False, help_text='Produkt godkendt til pantsystemet af en ESANI medarbejder', verbose_name='Godkendt'),
        ),
    ]
