# Generated by Django 4.2.2 on 2023-12-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0008_qrbag_historicalqrbag'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalqrbag',
            name='companybranch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esani_pantportal.companybranch'),
        ),
        migrations.AddField(
            model_name='historicalqrbag',
            name='kiosk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esani_pantportal.kiosk'),
        ),
        migrations.AddField(
            model_name='qrbag',
            name='companybranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esani_pantportal.companybranch'),
        ),
        migrations.AddField(
            model_name='qrbag',
            name='kiosk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esani_pantportal.kiosk'),
        ),
        migrations.AddConstraint(
            model_name='qrbag',
            constraint=models.CheckConstraint(check=models.Q(('companybranch__isnull', True), ('kiosk__isnull', True), _connector='OR'), name='has_only_companybranch_or_kiosk'),
        ),
    ]
