# Generated by Django 4.2.2 on 2023-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0009_historicalqrbag_companybranch_historicalqrbag_kiosk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(help_text='Modtager(e) af email', max_length=300, verbose_name='Modtager')),
                ('subject', models.CharField(help_text='Emailens emne', max_length=200, verbose_name='Emne')),
                ('body', models.TextField(help_text='Modtager(e) af email', max_length=300, verbose_name='Modtager')),
            ],
            options={
                'verbose_name': 'sentemail',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nej')], default=True, help_text='Brugeren har godkendt at modtage nyhedsbreve', verbose_name='Nyhedsbrev'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Brugerens emailadresse', max_length=254, verbose_name='Emailadresse'),
        ),
    ]
