# Generated by Django 4.2.2 on 2023-12-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0010_sentemail_user_newsletter_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, default=None, help_text='Pant konto nr. (valgfri)', null=True, verbose_name='konto nr.'),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, default=None, help_text='Pant konto nr. (valgfri)', null=True, verbose_name='konto nr.'),
        ),
        migrations.AlterField(
            model_name='kiosk',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, default=None, help_text='Pant konto nr. (valgfri)', null=True, verbose_name='konto nr.'),
        ),
    ]
