# Generated by Django 4.2.2 on 2024-01-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0011_alter_company_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='body',
            field=models.TextField(help_text='Emailens indhold', max_length=300, verbose_name='Indhold'),
        ),
    ]
