# Generated by Django 4.2.2 on 2024-01-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0012_alter_sentemail_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='permit_number',
        ),
        migrations.RemoveField(
            model_name='kiosk',
            name='permit_number',
        ),
        migrations.AlterField(
            model_name='company',
            name='cvr',
            field=models.PositiveIntegerField(help_text='CVR Nummer', unique=True, verbose_name='CVR-nummer'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invoice_mail',
            field=models.EmailField(blank=True, default=None, help_text='Mail adresse som faktura skal sendes til (valgfri)', max_length=254, null=True, verbose_name='Fakturamail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='municipality',
            field=models.CharField(blank=True, default='', help_text='Butikken eller firmaets hjemkommune (valgfri)', max_length=255, verbose_name='Kommune'),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='invoice_mail',
            field=models.EmailField(blank=True, default=None, help_text='Mail adresse som faktura skal sendes til (valgfri)', max_length=254, null=True, verbose_name='Fakturamail'),
        ),
        migrations.AlterField(
            model_name='kiosk',
            name='invoice_mail',
            field=models.EmailField(blank=True, default=None, help_text='Mail adresse som faktura skal sendes til (valgfri)', max_length=254, null=True, verbose_name='Fakturamail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Brugerens emailadresse', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Esanibruger'), (2, 'Butiksbruger'), (3, 'Virksomhedsbruger'), (4, 'Kioskbruger')], verbose_name='Brugertype'),
        ),
    ]
