# Generated by Django 4.2.2 on 2024-01-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0013_remove_company_permit_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_da', models.CharField(max_length=50)),
                ('name_kl', models.CharField(max_length=50)),
            ],
        ),
    ]
