# Generated by Django 4.2.2 on 2024-01-04 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import esani_pantportal.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0014_qrstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_change_reason', models.TextField(null=True)),
                ('product_name', models.CharField(help_text='Navn på det pågældende produkt', max_length=200, verbose_name='Produktnavn')),
                ('barcode', models.CharField(db_index=True, help_text='Stregkode for et indmeldt produkt', validators=[esani_pantportal.models.validate_barcode_length, esani_pantportal.models.validate_digit], verbose_name='Stregkode')),
                ('refund_value', models.PositiveIntegerField(default=200, help_text='Pantværdi, angivet i øre (100=1DKK, 25=0.25DKK)', verbose_name='Pantværdi')),
                ('approved', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nej')], default=False, help_text='Produkt godkendt til pantsystemet af en ESANI medarbejder', verbose_name='Godkendt')),
                ('material', models.CharField(choices=[('P', 'PET'), ('A', 'Aluminium'), ('S', 'Stål'), ('G', 'Glas')], help_text='Kategori for emballagens materiale.', verbose_name='Materiale')),
                ('height', models.PositiveIntegerField(help_text='Emballagens højde i millimeter', verbose_name='Højde')),
                ('diameter', models.PositiveIntegerField(help_text='Emballagens diameter i millimeter', verbose_name='Diameter')),
                ('weight', models.PositiveIntegerField(help_text='Tør/tom vægt af emballagen i gram', verbose_name='Vægt')),
                ('capacity', models.PositiveIntegerField(help_text='Emballagens volumen i milliliter', verbose_name='Volumen')),
                ('shape', models.CharField(choices=[('F', 'Flaske'), ('D', 'Dåse'), ('A', 'Anden')], help_text='Kategori for emballagens form.', verbose_name='Form')),
                ('danish', models.CharField(choices=[('J', 'Ja'), ('N', 'Nej'), ('U', 'Ukendt')], default='U', help_text='Der er Dansk pant på dette produkt', verbose_name='Dansk pant')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oprettet af')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
