# Generated by Django 4.2.2 on 2024-01-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0014_qrstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval_date',
            field=models.DateField(blank=True, default=None, help_text='Dato som dette produkt blev godkendt på', null=True, verbose_name='Godkendt dato'),
        ),
    ]
