# Generated by Django 4.2.2 on 2024-01-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0015_product_approval_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companybranch',
            options={'verbose_name': 'companybranch', 'verbose_name_plural': 'companybranches'},
        ),
        migrations.AlterModelOptions(
            name='kiosk',
            options={'verbose_name': 'kiosk', 'verbose_name_plural': 'kiosks'},
        ),
    ]
