# Generated by Django 4.2.2 on 2024-01-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0016_alter_companybranch_options_alter_kiosk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='approval_date',
            field=models.DateField(blank=True, default=None, help_text='Dato som dette produkt blev godkendt på', null=True, verbose_name='Godkendt dato'),
        ),
    ]
