# Generated by Django 4.2.2 on 2024-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0018_historicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='creation_date',
            field=models.DateField(blank=True, default=None, help_text='Dato som dette produkt blev oprettet på', null=True, verbose_name='Oprettelsesdato'),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateField(blank=True, default=None, help_text='Dato som dette produkt blev oprettet på', null=True, verbose_name='Oprettelsesdato'),
        ),
    ]
