# Generated by Django 4.2.2 on 2024-01-19 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0020_user_show_approval_date_user_show_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_file_name',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Navn på det importerede fil', max_length=200, verbose_name='Filnavn')),
                ('date', models.DateTimeField(help_text='Dato som filen blev importeret på', verbose_name='Importdato')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importjobs', to=settings.AUTH_USER_MODEL, verbose_name='Importeret af')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='import_job',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='Fil import som blev brugt for at importere dette produkt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esani_pantportal.importjob', verbose_name='Fil'),
        ),
        migrations.AddField(
            model_name='product',
            name='import_job',
            field=models.ForeignKey(blank=True, default=None, help_text='Fil import som blev brugt for at importere dette produkt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='esani_pantportal.importjob', verbose_name='Fil'),
        ),
    ]
