# Generated by Django 4.2.2 on 2024-01-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esani_pantportal', '0021_user_show_file_name_importjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositpayoutitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_items', to='esani_pantportal.product', verbose_name='Produkt'),
        ),
    ]
