# Generated by Django 4.2.2 on 2024-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0022_alter_depositpayoutitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybranch",
            name="qr_compensation",
            field=models.FloatField(
                default=0,
                help_text="Håndterings-godtgørelse for QR-poser, angivet i øre (100=1DKK, 25=0.25DKK)",
                verbose_name="Håndterings-godtgørelse for QR-poser",
            ),
        ),
        migrations.AddField(
            model_name="kiosk",
            name="qr_compensation",
            field=models.FloatField(
                default=0,
                help_text="Håndterings-godtgørelse for QR-poser, angivet i øre (100=1DKK, 25=0.25DKK)",
                verbose_name="Håndterings-godtgørelse for QR-poser",
            ),
        ),
    ]
