# Generated by Django 4.2.2 on 2024-01-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "esani_pantportal",
            "0023_companybranch_qr_compensation_kiosk_qr_compensation",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refundmethod",
            name="method",
        ),
    ]
