# Generated by Django 4.2.2 on 2024-01-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0024_remove_refundmethod_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depositpayoutitem",
            options={"ordering": ["-date"]},
        ),
    ]
