# Generated by Django 4.2.2 on 2024-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0025_alter_depositpayoutitem_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="depositpayout",
            old_name="filename",
            new_name="source_identifier",
        ),
        migrations.AddField(
            model_name="depositpayout",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("csv", "Clearing-rapporter (CSV)"),
                    ("api", "QR-sække (API)"),
                ],
                default="csv",
                max_length=3,
                verbose_name="Kilde-type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="depositpayoutitem",
            name="consumer_identity",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="depositpayoutitem",
            name="consumer_session_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="depositpayout",
            name="source_identifier",
            field=models.CharField(
                max_length=255, verbose_name="Kilde-ID (filnavn eller URL)"
            ),
        ),
    ]
