# Generated by Django 4.2.2 on 2024-01-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "esani_pantportal",
            "0026_rename_filename_depositpayout_source_identifier_and_more_updated",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RefundMethod",
            new_name="ReverseVendingMachine",
        ),
    ]

    atomic = False
