# Generated by Django 4.2.2 on 2024-01-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0027_rename_refundmethod_reversevendingmachine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reversevendingmachine",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Afdeling hvor denne maskine står",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rvms",
                to="esani_pantportal.companybranch",
                verbose_name="Afdeling",
            ),
        ),
        migrations.AlterField(
            model_name="reversevendingmachine",
            name="kiosk",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Butik hvor denne maskine står",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rvms",
                to="esani_pantportal.kiosk",
                verbose_name="Butik",
            ),
        ),
    ]
