# Generated by Django 4.2.2 on 2024-02-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0028_alter_reversevendingmachine_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="esani_customer_id",
        ),
        migrations.RemoveField(
            model_name="companybranch",
            name="esani_customer_id",
        ),
        migrations.RemoveField(
            model_name="kiosk",
            name="esani_customer_id",
        ),
    ]
