# Generated by Django 4.2.2 on 2024-02-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0029_remove_company_esani_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="product_name",
            field=models.CharField(
                help_text="Navn på det pågældende produkt",
                max_length=44,
                verbose_name="Produktnavn",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                help_text="Navn på det pågældende produkt",
                max_length=44,
                verbose_name="Produktnavn",
            ),
        ),
    ]
