# Generated by Django 4.2.2 on 2024-02-05 13:50
# Edited by Nick on 2024-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0030_alter_historicalproduct_product_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="qrbag",
            name="has_only_companybranch_or_kiosk",
        ),
        migrations.RenameField(
            model_name="qrbag",
            old_name="companybranch",
            new_name="company_branch"
        ),
        migrations.RenameField(
            model_name="historicalqrbag",
            old_name="companybranch",
            new_name="company_branch"
        ),
        migrations.AddConstraint(
            model_name="qrbag",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("company_branch__isnull", True), ("kiosk__isnull", True), _connector="OR"
                ),
                name="has_only_company_branch_or_kiosk",
            ),
        ),
    ]
