# Generated by Django 4.2.2 on 2024-02-07 13:24
# Edited by Nick on his birthday

from django.db import migrations, models


def set_pk(apps, schema_editor):
    qrbag = apps.get_model("esani_pantportal", "QRBag")
    qrbag_history = apps.get_model("esani_pantportal", "HistoricalQRBag")
    for pk, obj in enumerate(qrbag.objects.all()):
        obj.id = pk
        obj.save()

        for history_obj in qrbag_history.objects.filter(qr=obj.qr):
            history_obj.id = pk
            history_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0032_rename_branch_to_company_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqrbag",
            name="id",
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="qrbag",
            name="id",
            field=models.BigIntegerField(default=1),
        ),
        migrations.RunPython(set_pk),
        migrations.AlterField(
            model_name="qrbag",
            name="qr",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalqrbag",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="qrbag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
