# Generated by Django 4.2.2 on 2024-02-12 15:11
import os

from django.core.management import call_command
from django.db import migrations, models


def load_initial_data(apps, schema_editor):
    path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "0038_erpproductmapping_initial_data.json",
    )
    call_command("loaddata", path, verbosity=2)


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0037_company_invoice_company_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_number",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Varenummer i eksternt system (ERP)"
                    ),
                ),
                (
                    "rate",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Sats ('pris' pr. enhed) i øre",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=100, verbose_name="Tekst på varelinjer"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("deposit", "Pant"),
                            ("handling", "Håndteringsgodtgørelse"),
                            ("bag", "Pose"),
                        ],
                        max_length=10,
                        verbose_name="Overordnet type af varelinje",
                    ),
                ),
                (
                    "specifier",
                    models.CharField(
                        choices=[
                            ("rvm", "Pant eller håndteringsgodtgørelse, fra automat"),
                            ("bag", "Pant eller håndteringsgodtgørelse, fra QR-pose"),
                            ("0", "Små sække"),
                            ("1", "Store sække"),
                            ("9", "QR-koder til test"),
                        ],
                        max_length=10,
                        verbose_name="Specifik type af varelinje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eksternt varenummer",
                "verbose_name_plural": "Eksterne varenumre",
                "unique_together": {("category", "specifier")},
            },
        ),
        migrations.RunPython(load_initial_data),
    ]
