# Generated by Django 4.2.2 on 2024-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0039_user_show_company_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="show_approval_date",
            field=models.BooleanField(default=False, verbose_name="Godkendt dato"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_approved",
            field=models.BooleanField(default=True, verbose_name="Godkendt"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_branch",
            field=models.BooleanField(default=True, verbose_name="Butik"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_capacity",
            field=models.BooleanField(default=False, verbose_name="Volumen"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_company",
            field=models.BooleanField(default=True, verbose_name="Virksomhed"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_creation_date",
            field=models.BooleanField(default=False, verbose_name="Oprettelsesdato"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_danish",
            field=models.BooleanField(default=True, verbose_name="Dansk pant"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_diameter",
            field=models.BooleanField(default=False, verbose_name="Diameter"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=False, verbose_name="Mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_file_name",
            field=models.BooleanField(default=False, verbose_name="Filnavn"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_height",
            field=models.BooleanField(default=False, verbose_name="Højde"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_is_admin",
            field=models.BooleanField(
                default=True, verbose_name="Har admin-rettigheder"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_material",
            field=models.BooleanField(default=True, verbose_name="Materiale"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_newsletter",
            field=models.BooleanField(
                default=False, verbose_name="Modtager Nyhedsbreve"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_phone",
            field=models.BooleanField(default=False, verbose_name="Telefonnummer"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_shape",
            field=models.BooleanField(default=True, verbose_name="Form"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_weight",
            field=models.BooleanField(default=False, verbose_name="Vægt"),
        ),
    ]
