# Generated by Django 4.2.2 on 2024-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0042_cleanup_phone_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="municipality",
            field=models.CharField(
                choices=[
                    ("Avannaata Kommunia", "Avannaata Kommunia"),
                    ("Kommune Kujalleq", "Kommune Kujalleq"),
                    ("Kommune Qeqertalik", "Kommune Qeqertalik"),
                    ("Kommuneqarfik Sermersooq", "Kommuneqarfik Sermersooq"),
                    ("Qeqqata Kommunia", "Qeqqata Kommunia"),
                    ("Anden", "Anden"),
                ],
                help_text="Butikken eller firmaets registrerede kommunenavn",
                max_length=255,
                verbose_name="Kommune",
            ),
        ),
        migrations.AlterField(
            model_name="companybranch",
            name="municipality",
            field=models.CharField(
                choices=[
                    ("Avannaata Kommunia", "Avannaata Kommunia"),
                    ("Kommune Kujalleq", "Kommune Kujalleq"),
                    ("Kommune Qeqertalik", "Kommune Qeqertalik"),
                    ("Kommuneqarfik Sermersooq", "Kommuneqarfik Sermersooq"),
                    ("Qeqqata Kommunia", "Qeqqata Kommunia"),
                    ("Anden", "Anden"),
                ],
                help_text="Butikken eller firmaets registrerede kommunenavn",
                max_length=255,
                verbose_name="Kommune",
            ),
        ),
        migrations.AlterField(
            model_name="kiosk",
            name="municipality",
            field=models.CharField(
                choices=[
                    ("Avannaata Kommunia", "Avannaata Kommunia"),
                    ("Kommune Kujalleq", "Kommune Kujalleq"),
                    ("Kommune Qeqertalik", "Kommune Qeqertalik"),
                    ("Kommuneqarfik Sermersooq", "Kommuneqarfik Sermersooq"),
                    ("Qeqqata Kommunia", "Qeqqata Kommunia"),
                    ("Anden", "Anden"),
                ],
                help_text="Butikken eller firmaets registrerede kommunenavn",
                max_length=255,
                verbose_name="Kommune",
            ),
        ),
    ]
