# Generated by Django 4.2.2 on 2024-02-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0044_alter_company_municipality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositpayoutitem",
            name="qr_bag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_items",
                to="esani_pantportal.qrbag",
                verbose_name="QR-pose",
            ),
        ),
    ]
