# Generated by Django 4.2.2 on 2024-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0046_backfill_deposit_payout_item_qr_bag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositpayoutitem",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
