# Generated by Django 4.2.2 on 2024-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0047_alter_depositpayoutitem_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositpayoutitem",
            name="file_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
