# Generated by Django 4.2.2 on 2024-03-05 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0049_remove_user_show_approval_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPCreditNoteExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.UUIDField(unique=True, verbose_name="Fil-ID")),
                (
                    "from_date",
                    models.DateField(
                        verbose_name="Fra-dato for de eksporterede pantdata"
                    ),
                ),
                (
                    "to_date",
                    models.DateField(
                        verbose_name="Til-dato for de eksporterede pantdata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oprettelses-dato og -tid for denne eksport",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruger, der har oprettet denne fil-eksport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kreditnota-eksport til ERP",
                "verbose_name_plural": "Kreditnota-eksporter til ERP",
            },
        ),
    ]
