# Generated by Django 4.2.2 on 2024-03-07 15:03

from django.db import migrations, models
import esani_pantportal.models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0050_erpcreditnoteexport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositpayoutitem",
            name="barcode",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[
                    esani_pantportal.models.validate_barcode_length,
                    esani_pantportal.models.validate_digit,
                ],
            ),
        ),
    ]
