# Generated by Nick on 2024-03-04 10:50

from django.db import migrations


def create_manual_ERP_product_mapping(apps, schema_editor):
    model = apps.get_model("esani_pantportal", "ERPProductMapping")

    model.objects.create(
        item_number=103,
        rate=200,
        text="Pant (manuelt oprettet)",
        category="deposit",
        specifier="manual",
    )

    model.objects.create(
        item_number=203,
        rate=10,
        text="Håndteringsgodtgørelse (manuelt oprettet)",
        category="handling",
        specifier="manual",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0051_alter_depositpayoutitem_barcode"),
    ]

    operations = [migrations.RunPython(create_manual_ERP_product_mapping)]
