# Generated by Django 4.2.11 on 2024-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0053_alter_depositpayout_source_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositpayoutitem",
            name="compensation",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Håndterings-godtgørelse, angivet i øre (100=1DKK, 25=0.25DKK)",
                null=True,
                verbose_name="Håndterings-godtgørelse",
            ),
        ),
    ]
