# Generated by Django 4.2.11 on 2024-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0053_alter_depositpayout_source_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="closed",
            field=models.BooleanField(
                choices=[(True, "Ja"), (False, "Nej")],
                default=False,
                help_text="Produkt nedlagt af en ESANI medarbejder",
                verbose_name="Nedlagt",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="closed",
            field=models.BooleanField(
                choices=[(True, "Ja"), (False, "Nej")],
                default=False,
                help_text="Produkt nedlagt af en ESANI medarbejder",
                verbose_name="Nedlagt",
            ),
        ),
    ]
