# Generated by Django 4.2.11 on 2024-03-18 15:20

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0053_alter_depositpayout_source_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqrbag",
            name="status",
            field=django_fsm.FSMField(
                default="butik_oprettet", max_length=50, protected=True
            ),
        ),
        migrations.AlterField(
            model_name="qrbag",
            name="status",
            field=django_fsm.FSMField(
                default="butik_oprettet", max_length=50, protected=True
            ),
        ),
    ]
