# Generated by Django 4.2.11 on 2024-03-21 11:46

from django.db import migrations, models
import django_fsm
import esani_pantportal.models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0053_alter_depositpayout_source_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="state",
            field=django_fsm.FSMField(
                db_index=True, default="afventer", max_length=50, protected=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="state",
            field=django_fsm.FSMField(
                db_index=True, default="afventer", max_length=50, protected=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="barcode",
            field=models.CharField(
                help_text="Stregkode for et indmeldt produkt",
                validators=[
                    esani_pantportal.models.validate_barcode_length,
                    esani_pantportal.models.validate_digit,
                ],
                verbose_name="Stregkode",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                help_text="Stregkode for et indmeldt produkt",
                validators=[
                    esani_pantportal.models.validate_barcode_length,
                    esani_pantportal.models.validate_digit,
                ],
                verbose_name="Stregkode",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "slettet"), _negated=True),
                fields=("barcode",),
                name="barcode_unique_when_not_deleted",
            ),
        ),
    ]
