# Generated by Django 4.2.11 on 2024-03-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0055_populate_product_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproduct",
            name="approval_date",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="approval_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="product",
            name="creation_date",
        ),
    ]
