# Generated by Django 4.2.11 on 2024-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0057_historicalproduct_history_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="rejection",
            field=models.CharField(
                blank=True,
                help_text="Denne besked vises, hvis produktet er afvist, og alligevel forsøges scannet, etc.",
                null=True,
                verbose_name="Besked ved afvist produkt",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rejection",
            field=models.CharField(
                blank=True,
                help_text="Denne besked vises, hvis produktet er afvist, og alligevel forsøges scannet, etc.",
                null=True,
                verbose_name="Besked ved afvist produkt",
            ),
        ),
    ]
