# Generated by Django 4.2.11 on 2024-04-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0055_alter_companybranch_qr_compensation_and_more"),
        ("esani_pantportal", "0059_populate_approved_histories_without_creation"),
    ]

    operations = []
