# Generated by Django 4.2.11 on 2024-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0061_alter_historicalproduct_state_alter_product_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqrbag",
            name="status",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="qrbag",
            name="status",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
