# Generated by Django 4.2.11 on 2024-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0063_alter_depositpayoutitem_rvm_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companybranch",
            name="location_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Butikkens lokation ID (valgfri)",
                max_length=128,
                null=True,
                verbose_name="LokationsID",
            ),
        ),
        migrations.AlterField(
            model_name="kiosk",
            name="location_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Butikkens lokation ID (valgfri)",
                max_length=128,
                null=True,
                verbose_name="LokationsID",
            ),
        ),
    ]
