# Generated by Django 4.2.11 on 2024-10-31 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0063_alter_depositpayoutitem_rvm_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositpayoutitem",
            name="rvm_serial",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                validators=[django.core.validators.RegexValidator("\\d{1,128}")],
            ),
        ),
    ]
