# Generated by Django 4.2.20 on 2025-05-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0066_user_fasttrack_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrbag",
            options={"ordering": ["qr"]},
        ),
        migrations.RemoveField(
            model_name="historicalqrbag",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="qrbag",
            name="updated",
        ),
    ]
