# Generated by Django 4.2.20 on 2025-05-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "esani_pantportal",
            "0067_alter_qrbag_options_remove_historicalqrbag_updated_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Bynavn"),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="company",
            name="city_fk",
            field=models.ForeignKey(
                help_text="Butikken eller firmaets registrerede bynavn",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="esani_pantportal.city",
                verbose_name="By",
            ),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="city_fk",
            field=models.ForeignKey(
                help_text="Butikken eller firmaets registrerede bynavn",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="esani_pantportal.city",
                verbose_name="By",
            ),
        ),
        migrations.AddField(
            model_name="kiosk",
            name="city_fk",
            field=models.ForeignKey(
                help_text="Butikken eller firmaets registrerede bynavn",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="esani_pantportal.city",
                verbose_name="By",
            ),
        ),
    ]
