# Generated by Django 5.2.7 on 2025-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0070_update_city_fields_to_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositpayoutitem",
            name="consumer_identity",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
