# Generated by Django 5.2.7 on 2026-03-02 14:54

from django.db import migrations
from django.db.models import Max


def create_product(apps, schema_editor):
    from esani_pantportal.models import ProductState
    Product = apps.get_model("esani_pantportal", "Product")
    product, created = Product.objects.update_or_create(
        barcode="manual",
        defaults={
            "state": ProductState.DELETED,
            "material": "P",
            "height": 200,
            "diameter": 100,
            "weight": 50,
            "capacity": 200,
            "shape": "F",
        }
    )
    print(
        "%s %s (pk=%r)" % (
            "Created" if created else "Updated", product, product.pk
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0071_alter_depositpayoutitem_consumer_identity"),
    ]

    operations = [
        migrations.RunPython(create_product),
    ]
