# Generated by Django 5.2.7 on 2026-03-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esani_pantportal", "0072_create_product_barcode_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqrbag",
            name="hidden_reason",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="qrbag",
            name="hidden_reason",
            field=models.TextField(null=True),
        ),
    ]
